### ISSUE TITLE
Feature Request: Gist-like auto id attribute for headings with_toc_data extension

### ISSUE THREAD

**Issue by topher6345** [vmg/redcarpet#370]
When using the with_toc_data extension - 

in _config.yml

``` yml
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
```

`# Introduction` renders  `<h1 id="toc_0"> Introduction </h1>`

Could there be some way to have `# Introduction` render `<h1 id="introduction"> Introduction </h1>` like Github flavored markdown does when you write a  Gists?

This way, URL's could be given hashbangs 

example.com/blog/post.html#introduction

and Table of Contents could be written with more semantic markdown like this: 

`1. [Introduction](#introduction)`
