### ISSUE TITLE
Inline triple-backtick parsing

### ISSUE THREAD

**Issue by jbohren** [vmg/redcarpet#459]
I'm trying to render a readme from someone's Git repo with redcarpet with `:fenced_code_blocks` enabled but the author of [this markdown file](https://github.com/code-iai/ros_emacs_utils/blob/master/README.md#L60) has written sections with inline triple-backticks like the following:

```md
Once set up, you can start the REPL from your Emacs by pressing ```M-x slime```,
which means holding the ```Alt``` key and pressing ```x``` and then typing
```slime``` .
``` 

It appears that redcarpet does fine with the inline triple-backtick syntax except when it begins a line (like that last one in the section above). In that last case, however, it interprets it as a lexer and fails. See the bottom of this page for an example traceback: http://rosindex.github.io/r/ros_emacs_utils/github-code-iai-ros_emacs_utils/#indigo

Is this a bug, or is that something that should just be sanitized out in a preprocessor?

I might try it directly with [github/markup](https://github.com/github/markup/) and see how that does, since I'd like to handle a bunch of different formats anyway.

---

For reference, my [jekyll redcarpet config](https://github.com/rosindex/rosindex.github.io/blob/source/_config.yml#L20) is:

```yaml
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - no_intra_emphasis
    - with_toc_data
    - html_toc
    - tables
```
