### ISSUE TITLE
List not compiling

### ISSUE THREAD

**Issue by appkr** [vmg/redcarpet#543]
Silly question though...

The following has been failed in compiling. Did I miss something?

```markdown
---
# layout: post
# ...
---

### The Next "Big Thing" Security & Trust

#### Mobile Solutions

– Mobile financial services
- ...

#### Embedded Solutions

– M2M communications
– ...
```

Compiled and rendered is

<img width="1280" alt="2016-02-05 9 44 22" src="https://cloud.githubusercontent.com/assets/6471947/12846824/27a4985e-cc52-11e5-8a53-ccea86a3db28.png">

Below is the `_config.yml`

```yml
markdown: "redcarpet"
redcarpet:
  extensions:
    - smart
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - underline
    - highlight
    - quote
    - footnote_ref
highlighter: pygments

# ...
```
